import './build-tools/fullBuildSanitizer.js';
import { runStableEnvironmentCheck } from './build-tools/stableEnvironmentCheck.js';
import { runPrebuildIntegrityCheck } from './build-tools/prebuildIntegrityCheck.js';
import { runStrictDuplicateArtifactGuard } from './build-tools/strictDuplicateArtifactGuard.js';

runStrictDuplicateArtifactGuard('.');
runPrebuildIntegrityCheck('.');
runStableEnvironmentCheck('.');
runStrictDuplicateArtifactGuard('.');

const documentationNoopParser = {
  parseForESLint() {
    return {
      ast: {
        type: 'Program',
        body: [],
        sourceType: 'module',
        range: [0, 0],
        loc: { start: { line: 1, column: 0 }, end: { line: 1, column: 0 } },
        tokens: [],
        comments: [],
      },
      visitorKeys: { Program: [] },
      services: {},
    };
  },
};

const documentationJsxFiles = [
  '**/*.md.jsx',
  '**/*.json.jsx',
  '**/*.config.jsx',
  '**/src/components/**/*.md.jsx',
  '**/src/components/**/*.json.jsx',
  '**/src/components/**/*.config.jsx',
  '**/src/components/**/*.txt.jsx',
  '**/src/components/**/*.rst.jsx',
  '**/src/components/**/*.adoc.jsx',
  '**/src/components/**/*.yaml.jsx',
  '**/src/components/**/*.yml.jsx',
  '**/src/components/**/*.jsxe',
  '**/src/components/**/README*.jsx',
  '**/src/components/**/CERTIFIC*.jsx',
  '**/src/components/**/CERTIFICADO*.jsx',
  '**/src/components/**/CERTIFICACAO*.jsx',
  '**/src/components/**/MANIFESTO*.jsx',
  '**/src/components/**/VALIDACAO*.jsx',
  '**/src/components/**/CHECKLIST*.jsx',
  '**/src/components/**/PROVA*.jsx',
  '**/src/components/**/BLOQUEIO*.jsx',
  '**/src/components/**/BOTOES*.jsx',
  '**/src/components/**/INTEGRACAO*.jsx',
  '**/src/components/**/STATUS*.jsx',
  '**/src/components/**/ETAPAS*.jsx',
  '**/src/components/**/ETAPA*.jsx',
  '**/src/components/**/FASES*.jsx',
  '**/src/components/**/FASE*.jsx',
  '**/src/components/**/DEBUG*.jsx',
  '**/src/components/**/DIAGNOSTICO*.jsx',
  '**/src/components/**/CORRECAO*.jsx',
  '**/src/components/**/FLUXO*.jsx',
  '**/src/components/**/ZINDEX*.jsx',
  '**/components/**/README*.jsx',
  '**/components/**/CERTIFIC*.jsx',
  '**/components/**/CERTIFICADO*.jsx',
  '**/components/**/CERTIFICACAO*.jsx',
  '**/components/**/MANIFESTO*.jsx',
  '**/components/**/VALIDACAO*.jsx',
  '**/components/**/CHECKLIST*.jsx',
  '**/components/**/PROVA*.jsx',
  '**/components/**/BLOQUEIO*.jsx',
  '**/components/**/BOTOES*.jsx',
  '**/components/**/INTEGRACAO*.jsx',
  '**/components/**/STATUS*.jsx',
  '**/components/**/ETAPAS*.jsx',
  '**/components/**/ETAPA*.jsx',
  '**/components/**/FASES*.jsx',
  '**/components/**/FASE*.jsx',
  '**/components/**/DEBUG*.jsx',
  '**/components/**/DIAGNOSTICO*.jsx',
  '**/components/**/CORRECAO*.jsx',
  '**/components/**/FLUXO*.jsx',
  '**/components/**/ZINDEX*.jsx',
];

const documentationArtifactIgnores = [
  '**/src/components/**/*.md.jsx',
  '**/src/components/**/*.md.js',
  '**/src/components/**/*.json.jsx',
  '**/src/components/**/*.config.jsx',
  '**/src/components/**/*.txt.jsx',
  '**/src/components/**/*.rst.jsx',
  '**/src/components/**/*.adoc.jsx',
  '**/src/components/**/*.yaml.jsx',
  '**/src/components/**/*.yml.jsx',
  '**/src/components/**/*.jsxe',
  '**/src/components/**/commitlint.config.jsx',
  '**/src/components/**/README*.jsx',
  '**/src/components/**/CERTIFIC*.jsx',
  '**/src/components/**/CERTIFICADO*.jsx',
  '**/src/components/**/CERTIFICACAO*.jsx',
  '**/src/components/**/MANIFESTO*.jsx',
  '**/src/components/**/VALIDACAO*.jsx',
  '**/src/components/**/CHECKLIST*.jsx',
  '**/src/components/**/PROVA*.jsx',
  '**/src/components/**/BLOQUEIO*.jsx',
  '**/src/components/**/BOTOES*.jsx',
  '**/src/components/**/INTEGRACAO*.jsx',
  '**/src/components/**/STATUS*.jsx',
  '**/src/components/**/ETAPAS*.jsx',
  '**/src/components/**/ETAPA*.jsx',
  '**/src/components/**/FASES*.jsx',
  '**/src/components/**/FASE*.jsx',
  '**/src/components/**/DEBUG*.jsx',
  '**/src/components/**/DIAGNOSTICO*.jsx',
  '**/src/components/**/CORRECAO*.jsx',
  '**/src/components/**/FLUXO*.jsx',
  '**/src/components/**/ZINDEX*.jsx',
  '**/*.md.jsx',
  '**/*.json.jsx',
  '**/*.config.jsx',
  '**/*.txt.jsx',
  '**/*.rst.jsx',
  '**/*.adoc.jsx',
  '**/*.yaml.jsx',
  '**/*.yml.jsx',
  'src/components/**/*.md.jsx',
  'src/components/**/*.md.js',
  'src/components/**/*.json.jsx',
  'src/components/**/*.config.jsx',
  'src/components/**/*.txt.jsx',
  'src/components/**/*.rst.jsx',
  'src/components/**/*.adoc.jsx',
  'src/components/**/*.jsxe',
  'src/components/**/commitlint.config.jsx',
  'src/components/**/README*.jsx',
  'src/components/**/CERTIFIC*.jsx',
  'src/components/**/CERTIFICADO*.jsx',
  'src/components/**/CERTIFICACAO*.jsx',
  'src/components/**/MANIFESTO*.jsx',
  'src/components/**/VALIDACAO*.jsx',
  'src/components/**/CHECKLIST*.jsx',
  'src/components/**/PROVA*.jsx',
  'src/components/**/BLOQUEIO*.jsx',
  'src/components/**/BOTOES*.jsx',
  'src/components/**/INTEGRACAO*.jsx',
  'src/components/**/STATUS*.jsx',
  'src/components/**/ETAPA*.jsx',
  'src/components/**/ETAPAS*.jsx',
  'src/components/**/FASE*.jsx',
  'src/components/**/DEBUG*.jsx',
  'src/components/**/DIAGNOSTICO*.jsx',
  'src/components/**/CORRECAO*.jsx',
  'src/components/**/FLUXO*.jsx',
  'components/**/*.md.jsx',
  'components/**/*.json.jsx',
  'components/**/*.config.jsx',
  '**/*.md',
  '**/*.txt',
  '**/*.rst',
  '**/*.adoc',
  '**/*.yaml',
  '**/*.yml',
  '**/*.md.*',
  '**/*.txt.*',
  '**/*.rst.*',
  '**/*.adoc.*',
  '**/*.json.*',
  '**/*.config.*',
  '**/*.jsxe',
  '**/README*',
  '**/CERTIFIC*',
  '**/CERTIFICADO*',
  '**/CERTIFICACAO*',
  '**/MANIFESTO*',
  '**/VALIDACAO*',
  '**/CHECKLIST*',
  '**/PROVA*',
  '**/BLOQUEIO*',
  '**/BOTOES*',
  '**/INTEGRACAO*',
  '**/STATUS*',
  '**/ETAPA*',
  '**/ETAPAS*',
  '**/FASE*',
  '**/DEBUG*',
  '**/DIAGNOSTICO*',
  '**/CORRECAO*',
  '**/FLUXO*',
  '**/SISTEMA*',
  '**/RESUMO*',
  '**/CHANGELOG*',
  '**/ROADMAP*',
  '**/GUIA*',
  '**/DOC*',
  '**/UnidadesDeMedida*',
  '**/rhf_zod_report*',
];

export default [
  {
    ignores: [
      '**/components/**/*.md.jsx',
      '**/components/**/*.json.jsx',
      '**/components/**/*.config.jsx',
      '**/components/**/*.txt.jsx',
      '**/components/**/*.rst.jsx',
      '**/components/**/*.adoc.jsx',
      '**/components/**/*.jsxe',
      '**/components/**/README*.jsx',
      '**/components/**/CERTIFIC*.jsx',
      '**/components/**/CERTIFICADO*.jsx',
      '**/components/**/CERTIFICACAO*.jsx',
      '**/components/**/MANIFESTO*.jsx',
      '**/components/**/VALIDACAO*.jsx',
      '**/components/**/CHECKLIST*.jsx',
      '**/components/**/PROVA*.jsx',
      '**/components/**/BLOQUEIO*.jsx',
      '**/components/**/BOTOES*.jsx',
      '**/components/**/INTEGRACAO*.jsx',
      '**/components/**/STATUS*.jsx',
      '**/components/**/ETAPA*.jsx',
      '**/components/**/ETAPAS*.jsx',
      '**/components/**/FASE*.jsx',
      '**/components/**/DEBUG*.jsx',
      '**/components/**/DIAGNOSTICO*.jsx',
      '**/components/**/CORRECAO*.jsx',
      '**/components/**/FLUXO*.jsx',
      '**/components/**/ZINDEX*.jsx',
      '**/src/components/**/*.md.jsx',
      '**/src/components/**/*.json.jsx',
      '**/src/components/**/*.config.jsx',
      '**/src/components/**/*.txt.jsx',
      '**/src/components/**/*.rst.jsx',
      '**/src/components/**/*.adoc.jsx',
      '**/src/components/**/*.jsxe',
      '**/src/components/**/README*.jsx',
      '**/src/components/**/CERTIFIC*.jsx',
      '**/src/components/**/MANIFESTO*.jsx',
      '**/src/components/**/VALIDACAO*.jsx',
      '**/src/components/**/CHECKLIST*.jsx',
      '**/src/components/**/PROVA*.jsx',
      '**/src/components/**/BLOQUEIO*.jsx',
      '**/src/components/**/BOTOES*.jsx',
      '**/src/components/**/INTEGRACAO*.jsx',
      '**/src/components/**/STATUS*.jsx',
      '**/src/components/**/ETAPAS*.jsx',
      '**/src/components/**/ETAPA*.jsx',
      '**/src/components/**/FASES*.jsx',
      '**/src/components/**/FASE*.jsx',
      '**/src/components/**/DEBUG*.jsx',
      '**/src/components/**/DIAGNOSTICO*.jsx',
      '**/src/components/**/CORRECAO*.jsx',
      '**/src/components/**/FLUXO*.jsx',
      '**/src/components/**/ZINDEX*.jsx',
      'dist/**',
      'build/**',
      'node_modules/**',
      '.vite/**',
      'coverage/**',
      'tmp/**',
      'temp/**',
      'logs/**',
      'public/base44-local-*.json',
      'src/build-tools/**',
      'build-tools/**',
      ...documentationArtifactIgnores,
    ],
  },
  {
    files: documentationJsxFiles,
    languageOptions: {
      parser: documentationNoopParser,
    },
    rules: {},
  },
  {
    files: [
      '*.js',
      '*.jsx',
      'src/pages/**/*.{js,jsx}',
      'src/lib/**/*.{js,jsx}',
      'src/hooks/**/*.{js,jsx}',
      'src/api/**/*.{js,jsx}',
      'src/utils/**/*.{js,jsx}',
      'src/components/**/*.{js,jsx}',
      '!**/components/**/*.md.jsx',
      '!**/components/**/*.json.jsx',
      '!**/components/**/*.config.jsx',
      '!**/components/**/*.jsxe',
      '!**/components/**/README*.jsx',
      '!**/components/**/CERTIFIC*.jsx',
      '!**/components/**/CERTIFICADO*.jsx',
      '!**/components/**/CERTIFICACAO*.jsx',
      '!**/components/**/MANIFESTO*.jsx',
      '!**/components/**/VALIDACAO*.jsx',
      '!**/components/**/CHECKLIST*.jsx',
      '!**/components/**/PROVA*.jsx',
      '!**/components/**/BLOQUEIO*.jsx',
      '!**/components/**/BOTOES*.jsx',
      '!**/components/**/INTEGRACAO*.jsx',
      '!**/components/**/STATUS*.jsx',
      '!**/components/**/ETAPA*.jsx',
      '!**/components/**/ETAPAS*.jsx',
      '!**/components/**/FASE*.jsx',
      '!**/components/**/DEBUG*.jsx',
      '!**/components/**/DIAGNOSTICO*.jsx',
      '!**/components/**/CORRECAO*.jsx',
      '!**/components/**/FLUXO*.jsx',
      '!**/components/**/ZINDEX*.jsx',
      '!**/src/components/**/*.md.jsx',
      '!**/src/components/**/*.json.jsx',
      '!**/src/components/**/*.config.jsx',
      '!**/src/components/**/*.txt.jsx',
      '!**/src/components/**/*.rst.jsx',
      '!**/src/components/**/*.adoc.jsx',
      '!**/src/components/**/*.jsxe',
      '!**/src/components/**/README*.jsx',
      '!**/src/components/**/CERTIFIC*.jsx',
      '!**/src/components/**/MANIFESTO*.jsx',
      '!**/src/components/**/VALIDACAO*.jsx',
      '!**/src/components/**/CHECKLIST*.jsx',
      '!**/src/components/**/PROVA*.jsx',
      '!**/src/components/**/BLOQUEIO*.jsx',
      '!**/src/components/**/BOTOES*.jsx',
      '!**/src/components/**/INTEGRACAO*.jsx',
      '!**/src/components/**/STATUS*.jsx',
      '!**/src/components/**/ETAPAS*.jsx',
      '!**/src/components/**/ETAPA*.jsx',
      '!**/src/components/**/FASES*.jsx',
      '!**/src/components/**/FASE*.jsx',
      '!**/src/components/**/DEBUG*.jsx',
      '!**/src/components/**/DIAGNOSTICO*.jsx',
      '!**/src/components/**/CORRECAO*.jsx',
      '!**/src/components/**/FLUXO*.jsx',
      '!**/src/components/**/ZINDEX*.jsx',
      '!src/components/**/*.md.jsx',
      '!src/components/**/*.json.jsx',
      '!src/components/**/*.config.jsx',
      '!src/components/**/*.jsxe',
      '!src/components/**/README*.jsx',
      '!src/components/**/CERTIFIC*.jsx',
      '!src/components/**/CERTIFICADO*.jsx',
      '!src/components/**/CERTIFICACAO*.jsx',
      '!src/components/**/MANIFESTO*.jsx',
      '!src/components/**/VALIDACAO*.jsx',
      '!src/components/**/CHECKLIST*.jsx',
      '!src/components/**/PROVA*.jsx',
      '!src/components/**/BLOQUEIO*.jsx',
      '!src/components/**/BOTOES*.jsx',
      '!src/components/**/INTEGRACAO*.jsx',
      '!src/components/**/STATUS*.jsx',
      '!src/components/**/ETAPA*.jsx',
      '!src/components/**/ETAPAS*.jsx',
      '!src/components/**/FASE*.jsx',
      '!src/components/**/DEBUG*.jsx',
      '!src/components/**/DIAGNOSTICO*.jsx',
      '!src/components/**/CORRECAO*.jsx',
      '!src/components/**/FLUXO*.jsx',
    ],
    ignores: documentationArtifactIgnores,
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        console: 'readonly',
        globalThis: 'readonly',
        module: 'readonly',
        process: 'readonly',
        Deno: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        Blob: 'readonly',
        URL: 'readonly',
        fetch: 'readonly',
        Response: 'readonly',
        Request: 'readonly',
        Headers: 'readonly',
        FormData: 'readonly',
        File: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        React: 'readonly',
      },
    },
    rules: {
      'no-undef': 'error',
    },
  },
];