import fs from "node:fs";
import path from "node:path";

const documentationArtifactFilePattern = /(^|\/)(README|CERTIFICADO|CERTIFICACAO|CERTIFIC|MANIFESTO|VALIDACAO|CHECKLIST|PROVA|MIGRACAO|BLOQUEIO|DEBUG|DIAGNOSTICO|INTEGRACAO|RESUMO|CHANGELOG|ROADMAP|GUIA|DOCS?|STATUS|ETAPA|FASE|SISTEMA|BOTOES|CORRECAO|rhf_zod_report|UnidadesDeMedida)[^/]*(\.(md|txt|rst|adoc|json|config|js|jsx|ts|tsx))?$/i;
const documentationExtensionPattern = /\.(md|txt|rst|adoc|json|config)\.(js|jsx|ts|tsx)$/i;
const textDocumentationPattern = /\.(md|txt|rst|adoc)$/i;

const removeDocumentationArtifacts = (dir) => {
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const filePath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      removeDocumentationArtifacts(filePath);
      continue;
    }
    const normalized = filePath.replace(/\\/g, '/');
    const fileName = normalized.split('/').pop() || '';
    const shouldRemove = normalized.includes('/src/components/') && (
      textDocumentationPattern.test(fileName) ||
      documentationExtensionPattern.test(fileName) ||
      documentationArtifactFilePattern.test(fileName)
    );
    if (shouldRemove) fs.rmSync(filePath, { force: true });
  }
};

['node_modules/.vite', 'node_modules/.cache', 'dist/.vite', '.vite', '.eslintcache', 'build/.vite'].forEach((dir) => {
  try { fs.rmSync(path.resolve(process.cwd(), dir), { recursive: true, force: true }); } catch {}
});
removeDocumentationArtifacts(path.resolve(process.cwd(), 'src/components'));

const documentationMirrorPatterns = [
  "src/components/**/*.md.jsx",
  "src/components/**/*.txt.jsx",
  "src/components/**/*.rst.jsx",
  "src/components/**/*.adoc.jsx",
  "src/components/**/*.json.jsx",
  "src/components/**/*.config.jsx",
  "src/components/**/README*.jsx",
  "src/components/**/CERTIFICADO*.jsx",
  "src/components/**/CERTIFICACAO*.jsx",
  "src/components/**/MANIFESTO*.jsx",
  "src/components/**/VALIDACAO*.jsx",
  "src/components/**/CHECKLIST*.jsx",
  "src/components/**/PROVA*.jsx",
  "src/components/**/BLOQUEIO*.jsx",
  "src/components/**/STATUS*.jsx",
  "src/components/**/ETAPA*.jsx",
  "src/components/**/FASE*.jsx",
  "src/components/**/SISTEMA*.jsx",
  "src/components/**/DEBUG*.jsx",
  "src/components/**/DIAGNOSTICO*.jsx",
  "src/components/**/INTEGRACAO*.jsx",
  "src/components/**/RESUMO*.jsx",
  "components/**/*.md.jsx",
  "components/**/*.json.jsx",
  "components/**/*.config.jsx",
  "components/**/README*.jsx",
  "components/**/CERTIFIC*.jsx",
  "components/**/CHECKLIST*.jsx",
  "components/**/MANIFESTO*.jsx",
  "components/**/VALIDACAO*.jsx",
  "components/**/BLOQUEIO*.jsx",
  "components/**/BOTOES*.jsx",
  "components/**/INTEGRACAO*.jsx",
  "components/**/STATUS*.jsx",
  "components/**/PROVA*.jsx",
  "components/**/ETAPA*.jsx",
  "components/**/FASE*.jsx",
  "components/**/DEBUG*.jsx",
  "components/**/DIAGNOSTICO*.jsx",
  "components/**/CORRECAO*.jsx",
  "src/components/**/*.md.jsx",
  "**/src/components/**/*.md.jsx",
  "**/src/components/**/*.json.jsx",
  "**/src/components/**/*README*.jsx",
  "**/src/components/**/*CERTIFIC*.jsx",
  "**/src/components/**/*CHECKLIST*.jsx",
  "**/src/components/**/*MANIFESTO*.jsx",
  "**/src/components/**/*VALIDACAO*.jsx",
  "**/src/components/**/*BLOQUEIO*.jsx",
  "**/src/components/**/*BOTOES*.jsx",
  "**/src/components/**/*INTEGRACAO*.jsx",
  "**/src/components/**/*STATUS*.jsx",
  "**/src/components/**/*PROVA*.jsx",
  "**/*.md",
  "**/*.json",
  "**/*.config",
  "**/*.md.*",
  "**/*.json.*",
  "**/*.config.*",
  "**/*.md.jsx",
  "**/*.json.jsx",
  "src/**/*.md.jsx",
  "src/**/*.json.jsx",
  "src/**/README*.jsx",
  "src/**/CERTIFIC*.jsx",
  "src/**/CHECKLIST*.jsx",
  "src/**/BLOQUEIO*.jsx",
  "src/**/BOTOES*.jsx",
  "**/commitlint.config.jsx",
  "**/src/**/*.md",
  "**/src/**/*.json",
  "**/src/**/*.config",
  "**/src/**/*.md.*",
  "**/src/**/*.json.*",
  "**/src/**/*.config.*",
  "**/src/**/README*",
  "**/src/**/CERTIFICADO*",
  "**/src/**/CERTIFICACAO*",
  "**/src/**/MANIFESTO*",
  "**/src/**/STATUS*",
  "**/src/**/VALIDACAO*",
  "**/src/**/CHECKLIST*",
  "**/src/**/ETAPA*",
  "**/src/**/FASE*",
  "**/src/**/PROVA*",
  "**/src/**/SISTEMA*",
  "**/src/**/MIGRACAO*",
  "**/src/**/BLOQUEIO*",
  "**/src/**/DEBUG*",
  "**/src/**/DIAGNOSTICO*",
  "**/src/**/INTEGRACAO*",
  "**/src/**/RESUMO*",
  "**/src/**/CHANGELOG*",
  "**/src/**/ROADMAP*",
  "**/src/**/GUIA*",
  "**/src/**/DOC*",
  "**/src/**/UnidadesDeMedida*",
  "**/src/**/rhf_zod_report*",
  "**/components/**/README*",
  "**/components/**/CERTIFICADO*",
  "**/components/**/CERTIFICACAO*",
  "**/components/**/MANIFESTO*",
  "**/components/**/STATUS*",
  "**/components/**/VALIDACAO*",
  "**/components/**/CHECKLIST*",
  "**/components/**/ETAPA*",
  "**/components/**/FASE*",
  "**/components/**/PROVA*",
  "**/components/**/SISTEMA*",
  "**/components/**/BLOQUEIO*",
  "**/components/**/BOTOES*",
  "**/components/**/INTEGRACAO*",
  "**/components/**/UnidadesDeMedida*",
  "**/components/**/rhf_zod_report*",
  "src/components/**/*.{md,json,config}.jsx",
  "src/components/**/*.{md,json,config}.*",
  "src/components/**/[A-Z0-9_]*.jsx",
  "src/components/**/[A-Z0-9_]*.md.jsx",
];

export default [
  {
    ignores: [
      "**/*.md.jsx",
      "**/*.txt.jsx",
      "**/*.rst.jsx",
      "**/*.adoc.jsx",
      "**/*.json.jsx",
      "**/*.config.jsx",
      "**/*.md.js",
      "**/*.json.js",
      "**/*.config.js",
      "**/README*",
      "**/CERTIFICADO*",
      "**/CERTIFICACAO*",
      "**/CERTIFIC*",
      "**/CERTIFICADO*.jsx",
      "**/CERTIFICACAO*.jsx",
      "**/MANIFESTO*",
      "**/VALIDACAO*",
      "**/CHECKLIST*",
      "**/PROVA*",
      "**/BLOQUEIO*",
      "**/BOTOES*",
      "**/INTEGRACAO*",
      "**/STATUS*",
      "**/ETAPA*",
      "**/FASE*",
      "**/DEBUG*",
      "**/DIAGNOSTICO*",
      "**/CORRECAO*",
      "**/rhf_zod_report*",
      "**/UnidadesDeMedida*",
      "dist/**",
      "build/**",
      "node_modules/**",
      ...documentationMirrorPatterns,
    ],
  },
  {
    files: ["src/**/*.{js,jsx}", "*.{js,jsx}"],
    ignores: [
      "components/**/*.md.jsx",
      "components/**/*.json.jsx",
      "components/**/*.config.jsx",
      "components/**/README*.jsx",
      "components/**/CERTIFIC*.jsx",
      "components/**/CHECKLIST*.jsx",
      "components/**/MANIFESTO*.jsx",
      "components/**/VALIDACAO*.jsx",
      "components/**/BLOQUEIO*.jsx",
      "components/**/BOTOES*.jsx",
      "components/**/INTEGRACAO*.jsx",
      "components/**/STATUS*.jsx",
      "components/**/PROVA*.jsx",
      "components/**/ETAPA*.jsx",
      "components/**/FASE*.jsx",
      "components/**/DEBUG*.jsx",
      "components/**/DIAGNOSTICO*.jsx",
      "components/**/CORRECAO*.jsx",
      "src/components/**/*.md.jsx",
      "**/src/components/**/*.md.jsx",
      "**/components/**/*.md.jsx",
      "src/components/**/*.json.jsx",
      "src/components/**/*.config.jsx",
      "src/components/**/*README*.jsx",
      "src/components/**/*CERTIFIC*.jsx",
      "src/components/**/*CHECKLIST*.jsx",
      "src/components/**/*MANIFESTO*.jsx",
      "src/components/**/*VALIDACAO*.jsx",
      "src/components/**/*BLOQUEIO*.jsx",
      "src/components/**/*BOTOES*.jsx",
      "src/components/**/*INTEGRACAO*.jsx",
      ...documentationMirrorPatterns,
      "src/components/sistema/[A-Z]*.jsx",
      "src/components/sistema/[A-Z]*.md.jsx",
      "src/components/chatbot/*.md.jsx",
      "src/components/comercial/*.md.jsx",
      "src/components/docs/**/*.md.jsx",
      "src/components/lib/*.md.jsx",
      "src/components/lib/*.json.jsx",
      "src/components/logistica/*.md.jsx",
      "src/components/portal/*.md.jsx",
      "src/components/reports/*.json.jsx",
    ],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        Blob: "readonly",
        URL: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        React: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
    },
  },
];