import { runStableEnvironmentCheck } from './build-tools/stableEnvironmentCheck.js';
import { runPrebuildIntegrityCheck } from './build-tools/prebuildIntegrityCheck.js';
import { runStrictDuplicateArtifactGuard } from './build-tools/strictDuplicateArtifactGuard.js';

runStrictDuplicateArtifactGuard('.');
runPrebuildIntegrityCheck('.');
runStableEnvironmentCheck('.');
runStrictDuplicateArtifactGuard('.');

const documentationArtifactIgnores = [
  'src/components/**/*.md.jsx',
  'src/components/**/*.md.js',
  'src/components/**/*.json.jsx',
  'src/components/**/*.config.jsx',
  'src/components/**/*.txt.jsx',
  'src/components/**/*.rst.jsx',
  'src/components/**/*.adoc.jsx',
  'src/components/**/*.jsxe',
  'src/components/**/commitlint.config.jsx',
  'src/components/**/README*.jsx',
  'src/components/**/CERTIFIC*.jsx',
  'src/components/**/CERTIFICADO*.jsx',
  'src/components/**/CERTIFICACAO*.jsx',
  'src/components/**/MANIFESTO*.jsx',
  'src/components/**/VALIDACAO*.jsx',
  'src/components/**/CHECKLIST*.jsx',
  'src/components/**/PROVA*.jsx',
  'src/components/**/BLOQUEIO*.jsx',
  'src/components/**/BOTOES*.jsx',
  'src/components/**/INTEGRACAO*.jsx',
  'src/components/**/STATUS*.jsx',
  'src/components/**/ETAPA*.jsx',
  'src/components/**/ETAPAS*.jsx',
  'src/components/**/FASE*.jsx',
  'src/components/**/DEBUG*.jsx',
  'src/components/**/DIAGNOSTICO*.jsx',
  'src/components/**/CORRECAO*.jsx',
  'src/components/**/FLUXO*.jsx',
  'components/**/*.md.jsx',
  'components/**/*.json.jsx',
  'components/**/*.config.jsx',
  '**/*.md',
  '**/*.txt',
  '**/*.rst',
  '**/*.adoc',
  '**/*.yaml',
  '**/*.yml',
  '**/*.md.*',
  '**/*.txt.*',
  '**/*.rst.*',
  '**/*.adoc.*',
  '**/*.json.*',
  '**/*.config.*',
  '**/*.jsxe',
  '**/README*',
  '**/CERTIFIC*',
  '**/CERTIFICADO*',
  '**/CERTIFICACAO*',
  '**/MANIFESTO*',
  '**/VALIDACAO*',
  '**/CHECKLIST*',
  '**/PROVA*',
  '**/BLOQUEIO*',
  '**/BOTOES*',
  '**/INTEGRACAO*',
  '**/STATUS*',
  '**/ETAPA*',
  '**/ETAPAS*',
  '**/FASE*',
  '**/DEBUG*',
  '**/DIAGNOSTICO*',
  '**/CORRECAO*',
  '**/FLUXO*',
  '**/SISTEMA*',
  '**/RESUMO*',
  '**/CHANGELOG*',
  '**/ROADMAP*',
  '**/GUIA*',
  '**/DOC*',
  '**/UnidadesDeMedida*',
  '**/rhf_zod_report*',
];

export default [
  {
    ignores: [
      'dist/**',
      'build/**',
      'node_modules/**',
      '.vite/**',
      'coverage/**',
      'tmp/**',
      'temp/**',
      'logs/**',
      'public/base44-local-*.json',
      'src/build-tools/**',
      'build-tools/**',
      ...documentationArtifactIgnores,
    ],
  },
  {
    files: [
      '*.js',
      '*.jsx',
      'src/pages/**/*.{js,jsx}',
      'src/lib/**/*.{js,jsx}',
      'src/hooks/**/*.{js,jsx}',
      'src/api/**/*.{js,jsx}',
      'src/utils/**/*.{js,jsx}',
      'src/components/**/*.{js,jsx}',
      '!src/components/**/*.md.jsx',
      '!src/components/**/*.json.jsx',
      '!src/components/**/*.config.jsx',
      '!src/components/**/*.jsxe',
      '!src/components/**/README*.jsx',
      '!src/components/**/CERTIFIC*.jsx',
      '!src/components/**/CERTIFICADO*.jsx',
      '!src/components/**/CERTIFICACAO*.jsx',
      '!src/components/**/MANIFESTO*.jsx',
      '!src/components/**/VALIDACAO*.jsx',
      '!src/components/**/CHECKLIST*.jsx',
      '!src/components/**/PROVA*.jsx',
      '!src/components/**/BLOQUEIO*.jsx',
      '!src/components/**/BOTOES*.jsx',
      '!src/components/**/INTEGRACAO*.jsx',
      '!src/components/**/STATUS*.jsx',
      '!src/components/**/ETAPA*.jsx',
      '!src/components/**/ETAPAS*.jsx',
      '!src/components/**/FASE*.jsx',
      '!src/components/**/DEBUG*.jsx',
      '!src/components/**/DIAGNOSTICO*.jsx',
      '!src/components/**/CORRECAO*.jsx',
      '!src/components/**/FLUXO*.jsx',
    ],
    ignores: documentationArtifactIgnores,
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        console: 'readonly',
        globalThis: 'readonly',
        module: 'readonly',
        process: 'readonly',
        Deno: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        Blob: 'readonly',
        URL: 'readonly',
        fetch: 'readonly',
        Response: 'readonly',
        Request: 'readonly',
        Headers: 'readonly',
        FormData: 'readonly',
        File: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        React: 'readonly',
      },
    },
    rules: {
      'no-undef': 'error',
    },
  },
];